version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '16708:16708'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      replicas: 1

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '17229:17229'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:16708
      - KAFKA_LISTENERS=PLAINTEXT://:17229
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:17229
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    deploy:
      replicas: 1

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '18538:18538'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:17229
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:16708
    deploy:
      replicas: 1

  flight_service:
    image: 'burdakemilia/distribiutedflighttracker-flight_service:latest'
    ports:
      - '16709:16709'
    deploy:
      replicas: 1

  booking_service:
    image: 'burdakemilia/distribiutedflighttracker-booking_service:latest'
    ports:
      - '17230:17230'
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:17229
      - ALGORITHM=HS256
      - USER_KEY=dev-user-super-secret-key
    deploy:
      replicas: 1

  user_service:
    image: 'burdakemilia/distribiutedflighttracker-user_service:latest'
    ports:
      - '18539:18539'
    environment:
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - ALGORITHM=HS256
      - SECRET_KEY=dev-user-super-secret-key
    deploy:
      replicas: 1

  gateway_service:
    image: 'burdakemilia/distribiutedflighttracker-gateway_service:latest'
    ports:
      - '16710:16710'
    deploy:
      replicas: 1

networks:
  default:
    external:
      name: my-overlay-network
