"""Flight table extention

Revision ID: 93ee1373910f
Revises: 070b75140fa3
Create Date: 2024-05-19 13:31:50.417535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ee1373910f'
down_revision: Union[str, None] = '070b75140fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('time_departure', sa.Time(), nullable=True))
    op.add_column('flight', sa.Column('time_arrival', sa.Time(), nullable=True))
    op.add_column('flight', sa.Column('flight_time', sa.Integer(), nullable=True))
    op.add_column('flight', sa.Column('id_arrival_next_day', sa.Integer(), nullable=True))
    op.add_column('flight', sa.Column('is_dreamliner', sa.Boolean(), nullable=True))
    op.add_column('flight', sa.Column('checked_baggage', sa.Boolean(), nullable=True))
    op.add_column('flight', sa.Column('hand_luggage', sa.Boolean(), nullable=True))
    op.add_column('flight', sa.Column('food', sa.Boolean(), nullable=True))
    op.add_column('flight', sa.Column('update_data', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_flight_flight_time'), 'flight', ['flight_time'], unique=False)
    op.create_index(op.f('ix_flight_time_arrival'), 'flight', ['time_arrival'], unique=False)
    op.create_index(op.f('ix_flight_time_departure'), 'flight', ['time_departure'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_time_departure'), table_name='flight')
    op.drop_index(op.f('ix_flight_time_arrival'), table_name='flight')
    op.drop_index(op.f('ix_flight_flight_time'), table_name='flight')
    op.drop_column('flight', 'update_data')
    op.drop_column('flight', 'food')
    op.drop_column('flight', 'hand_luggage')
    op.drop_column('flight', 'checked_baggage')
    op.drop_column('flight', 'is_dreamliner')
    op.drop_column('flight', 'id_arrival_next_day')
    op.drop_column('flight', 'flight_time')
    op.drop_column('flight', 'time_arrival')
    op.drop_column('flight', 'time_departure')
    # ### end Alembic commands ###
