"""Initial migration

Revision ID: ad580082f9a9
Revises: e9de90eb4455
Create Date: 2024-04-10 16:28:05.963665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad580082f9a9'
down_revision: Union[str, None] = 'e9de90eb4455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('flight', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('flight', sa.Column('price', sa.Float(), nullable=True))
    op.drop_index('ix_flight_date_end', table_name='flight')
    op.drop_index('ix_flight_date_start', table_name='flight')
    op.drop_index('ix_flight_destinations', table_name='flight')
    op.create_index(op.f('ix_flight_date'), 'flight', ['date'], unique=False)
    op.create_index(op.f('ix_flight_destination'), 'flight', ['destination'], unique=False)
    op.create_index(op.f('ix_flight_price'), 'flight', ['price'], unique=False)
    op.drop_column('flight', 'date_start')
    op.drop_column('flight', 'date_end')
    op.drop_column('flight', 'destinations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('destinations', sa.VARCHAR(), nullable=True))
    op.add_column('flight', sa.Column('date_end', sa.DATETIME(), nullable=True))
    op.add_column('flight', sa.Column('date_start', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_flight_price'), table_name='flight')
    op.drop_index(op.f('ix_flight_destination'), table_name='flight')
    op.drop_index(op.f('ix_flight_date'), table_name='flight')
    op.create_index('ix_flight_destinations', 'flight', ['destinations'], unique=False)
    op.create_index('ix_flight_date_start', 'flight', ['date_start'], unique=False)
    op.create_index('ix_flight_date_end', 'flight', ['date_end'], unique=False)
    op.drop_column('flight', 'price')
    op.drop_column('flight', 'date')
    op.drop_column('flight', 'destination')
    # ### end Alembic commands ###
